void test_segment()
{
  clear_lcd();
  lcd_LB_on;
  delay(500);
  lcd_LB_off;
  
  clear_lcd();
  lcd_clk_1_on;
  lcd_clk_2_on;
  lcd_clk_3_on;
  lcd_clk_4_on;
  lcd_A_on;
  lcd_clk_1_off;
  lcd_clk_2_off;
  lcd_clk_3_off;
  lcd_clk_4_off;
  delay(500);

  clear_lcd();
  lcd_clk_1_on;
  lcd_clk_2_on;
  lcd_clk_3_on;
  lcd_clk_4_on;
  lcd_B_on;
  lcd_clk_1_off;
  lcd_clk_2_off;
  lcd_clk_3_off;
  lcd_clk_4_off;
  delay(500);

  clear_lcd();
  lcd_clk_1_on;
  lcd_clk_2_on;
  lcd_clk_3_on;
  lcd_clk_4_on;
  lcd_C_on;
  lcd_clk_1_off;
  lcd_clk_2_off;
  lcd_clk_3_off;
  lcd_clk_4_off;
  delay(500);

  clear_lcd();
  lcd_clk_1_on;
  lcd_clk_2_on;
  lcd_clk_3_on;
  lcd_clk_4_on;
  lcd_D_on;
  lcd_clk_1_off;
  lcd_clk_2_off;
  lcd_clk_3_off;
  lcd_clk_4_off;
  delay(500);

  clear_lcd();
  lcd_clk_1_on;
  lcd_clk_2_on;
  lcd_clk_3_on;
  lcd_clk_4_on;
  lcd_E_on;
  lcd_clk_1_off;
  lcd_clk_2_off;
  lcd_clk_3_off;
  lcd_clk_4_off;
  delay(500);

  clear_lcd();
  lcd_clk_1_on;
  lcd_clk_2_on;
  lcd_clk_3_on;
  lcd_clk_4_on;
  lcd_F_on;
  lcd_clk_1_off;
  lcd_clk_2_off;
  lcd_clk_3_off;
  lcd_clk_4_off;
  delay(500);

  clear_lcd();
  lcd_clk_1_on;
  lcd_clk_2_on;
  lcd_clk_3_on;
  lcd_clk_4_on;
  lcd_G_on;
  lcd_clk_1_off;
  lcd_clk_2_off;
  lcd_clk_3_off;
  lcd_clk_4_off;
  delay(500);

  clear_lcd();
  lcd_clk_1_on;
  lcd_clk_2_on;
  lcd_clk_3_on;
  lcd_clk_4_on;
  lcd_dot_on;
  lcd_clk_1_off;
  lcd_clk_2_off;
  lcd_clk_3_off;
  lcd_clk_4_off;
  delay(500);
}
